include ./Makefile.comm


AR        = ar
ARFLAGS   = rv
CFLAGS    = -Wall
TARGET    = libtest


# pack
$(TARGET):$(OBJ)
 @mkdir -p $(OUTPUT)
 $(AR) $(ARFLAGS) $(OUTPUT)/$(TARGET)_$(VERSION).a $(OBJ)
 #@$(RM) $(OBJ)
